#!/usr/bin/env bash

set -u

# source global variables
SCRIPT_FOLDER_PATH=$(cd "$(dirname "$0")"; pwd; cd - > /dev/null)
source "$SCRIPT_FOLDER_PATH/Docker.Config"
source "$SCRIPT_FOLDER_PATH/Docker.Utils"

# input .dSYM
dsymDirectory="$MAC_FOLDER_PATH/build/Docker.app.dSYM"
# output .dSYM.zip
zipDirectory="$MAC_FOLDER_PATH/build"

# zip the dSYM
LogImportant "Creating Docker.app.dSYM.zip"
LogImportant "Source:      $dsymDirectory"
LogImportant "Destination: $zipDirectory/Docker.app.dSYM.zip"

if [ ! -d "$dsymDirectory" ]; then
  LogError "Could not find \"$dsymDirectory\". Did you build it from command line ?"
fi
if [ ! -d "$zipDirectory" ]; then
  LogError "Output directory \"$zipDirectory\" does not exist"
fi
Log "Removing previous .zip"
Execute "rm -rf $zipDirectory/Docker.app.dSYM.zip"
zip -r "$zipDirectory/Docker.app.dSYM.zip" "$dsymDirectory"
if [ $? -eq 0 ]; then
  LogCompleted "Docker.app.dSYM.zip created successfully"
else
  LogError "Docker.app.dSYM.zip creation failed"
fi
