// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 1
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){





var Ba=this,Ca=function(){var a=YT.Player,b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},Da=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Ea=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Fa=function(a){if(null==a)return String(a);var b=Ea.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Ga=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},la=function(a){if(!a||"object"!=Fa(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Ga(a,"constructor")&&!Ga(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Ga(a,b)},Ha=function(a,b){var c=b||("array"==Fa(a)?[]:{}),d;for(d in a)if(Ga(a,d)){var e=a[d];"array"==Fa(e)?("array"!=Fa(c[d])&&(c[d]=[]),c[d]=Ha(e,c[d])):la(e)?(la(c[d])||(c[d]={}),c[d]=Ha(e,c[d])):c[d]=e}return c};var pa=null,Ja=Math.random(),Ka=null,La=null,ya=!1,Ma={},Na={},za={};var Oa,Pa,Qa,Ra,Sa,Ta,Ua,Va,Xa,Ya,Za,$a,ab,bb,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,ob,qb,rb,sb,tb,ub,vb,wb,xb,yb,zb,Ab,Bb,Cb,Db,Eb,Fb,Gb,Hb,Ib,Jb,Lb,Nb,Ob,Pb,Qb,Rb,Sb,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,T,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,qd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,
de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,Ye,Ze;
(function(){var a=function(a){return{toString:function(){return a}}};Oa=a("");Pa=a("0");Qa="";Ra=a("");Sa=a("");Ta=a("");Ua=a("");Va=a("");Xa=a("");Ya=a("");Za=a("");$a=a("2");ab=a("3");bb=a("");cb=a("");db=a("");
eb=a("");fb=a("");gb=a("");hb=a("");ib=a("");jb=a("");kb=a("");lb=a("");mb=a("");ob=a("");qb=a("");rb=a("");sb=a("");tb=a("");
ub=a("");vb=a("");wb=a("");xb=a("");yb=a("");zb=a("");Ab=a("");Bb=a("4");Cb=a("");Db=a("");Eb=a("");Fb=a("");Gb=a("");Hb=a("");Ib=a("");Jb=a("");Lb=a("");Nb=a("");
Ob=a("");Pb=a("");Qb=a("");Rb=a("");Sb=a("");Tb=a("");Ub=a("");Vb=a("");Wb=a("5");Xb=a("");Yb=a("");Zb=a("6");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("");
ec=a("");fc=a("");gc=a("");hc=a("7");ic=a("");jc=a("8");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("9");sc=a("");tc=a("");
uc=a("");vc=a("");xc=a("");yc=a("");zc=a("");Ac=a("");Bc=a("");Cc=a("");Dc=a("");Ec=a("");Fc=a("");Gc=a("10");Hc=a("");Ic=a("16");Jc=a("17");Kc=a("");Lc=a("");
Mc=a("");T=a("");Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("11");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("");Xc=a("");Yc=a("");Zc=a("");$c=a("");ad=a("");bd=a("12");cd=a("");dd=a("");
ed=a("");fd=a("");gd=a("");hd=a("");id=a("");jd=a("");kd=a("");ld=a("");md=a("");nd=a("");qd=a("");td=a("");ud=a("");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");
Cd=a("");Dd=a("");Ed=a("");Fd=a("");Gd=a("");Hd=a("");Id=a("");Jd=a("");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");
Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("");$d=a("");ae=a("");be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("");
ke=a("14");le=a("");me=a("");ne=a("");oe=a("");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");
Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie="";Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");Oe=a("15");Pe=a("");Qe=a("");Re=a("");
Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("")})();var $e=function(){},N=function(a){return"function"==typeof a},af=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},bf=function(a){return"number"==Fa(a)&&!isNaN(a)},cf=function(a){return/^[0-9]+$/.test(a)},df=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},ef=function(a){return a?a.replace(/^\s+|\s+$/g,""):""},O=function(a){return Math.round(Number(a))||0},ha=function(a){return"false"==
String(a).toLowerCase()?!1:!!a},ff=function(a){var b=[];if(af(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},I=function(){return new Date},gf=function(a,b){if(!bf(a)||!bf(b)||a>b)a=0,b=2147483647;return Math.round(Math.random()*(b-a)+a)},hf=function(){this.prefix="gtm.";this.values={}};hf.prototype.set=function(a,b){this.values[this.prefix+a]=b};hf.prototype.get=function(a){return this.values[this.prefix+a]};hf.prototype.contains=function(a){return void 0!==this.get(a)};
var jf=function(a,b,c){try{if(!a[gd])return a[Gc](a,b||$e,c||$e);c&&c()}catch(d){}return!1},kf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=ef(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},lf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},mf=function(a){return function(){return a("GTM-WLGFZV")}},nf=function(a){for(var b=0;b<a.length;b++)a[b]()},of=I().getTime(),ka=function(){return"gtm"+
of++},ma=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},pf=function(a,b,c){a.prototype["gtm_proxy_"+b]=a.prototype[b];a.prototype[b]=c},qf=function(a){return null!==a&&void 0!==a&&void 0!==a.length},rf=function(a,b){0==b?a.Va=!0:a.complete=!0;var c=a.g;a.s&&(a.s.Ga[c]=b);Ma[c]&&(Ma[c].state=b)},sf=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var H=window,R=document,vf=navigator,M=function(a,b,c){var d=H[a];H[a]=void 0===d||c?b:d;return H[a]},Q=function(a,b,c,d){return(d||"http:"!=H.location.protocol?a:b)+c},wf=function(a){var b=R.getElementsByTagName("script")[0]||R.body||R.head;b.parentNode.insertBefore(a,b)},oa=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},r=function(a,b,c){var d=R.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;oa(d,b);c&&(d.onerror=c);wf(d)},da=function(a,b){var c=R.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";wf(c);oa(c,b);void 0!==a&&(c.src=a);return c},G=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},U=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},x=function(a){H.setTimeout(a,0)},ra=!1,
sa=[],xf=function(a){if(!ra){var b=R.createEventObject,c="complete"==R.readyState,d="interactive"==R.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){ra=!0;for(var e=0;e<sa.length;e++)sa[e]()}sa.push=function(){for(var a=0;a<arguments.length;a++)x(arguments[a]);return 0}}},Ef=0,Ff=function(){if(!ra&&140>Ef){Ef++;try{R.documentElement.doScroll("left"),xf()}catch(a){H.setTimeout(Ff,50)}}},Hf=function(a){var b=R.getElementById(a);if(b&&Gf(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(Gf(document.all[a][c],
"id")==a)return document.all[a][c];return b},Gf=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},If=function(a){return a.target||a.srcElement||{}},wa=function(a){var b=R.createElement("div");b.innerHTML="A<div>"+a+"</div>";for(var b=b.lastChild,c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},Jf=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;for(var e=a,d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&
(e=null);return e},Kf=!1,Lf=[],Mf=function(){if(!Kf){Kf=!0;for(var a=0;a<Lf.length;a++)Lf[a]()}},Nf=function(a){a=a||H;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},ta=function(a){window.console&&window.console.log&&window.console.log(a)};var Of=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||H.location.protocol.replace(":","")).toLowerCase();switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||H.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:H.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=df(d||[],k[k.length-
1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");if(e)a:{for(var m=f.split("&"),l=0;l<m.length;l++){var n=m[l].split("=");if(decodeURIComponent(n[0]).replace(/\+/g," ")==e){f=decodeURIComponent(n.slice(1).join("=")).replace(/\+/g," ");break a}}f=void 0}break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},Pf=function(a){var b="";a&&a.href&&(b=a.hash?a.href.replace(a.hash,""):a.href);return b},xa=function(a){var b=R.createElement("a");
a&&(b.href=a);return b};var ca=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ba=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=Of(xa(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1},ga=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null};var aa=function(a,b,c){r(a,b,c)},C=H,Aa=function(a,b){C[a]=b},p=function(a,b,c){b&&(void 0===C[a]||c&&!C[a])&&(C[a]=b);return C[a]},u=function(a,b,c){return("https:"==H.location.protocol?a:b)+c};var Qf=new hf,Rf={},Tf={set:function(a,b){Ha(Sf(a,b),Rf)},get:function(a){return J(a,2)},reset:function(){Qf=new hf;Rf={}}},J=function(a,b){if(2==b){for(var c=Rf,d=a.split("."),e=0;e<d.length;e++){if(void 0===c[d[e]])return;c=c[d[e]]}return c}return Qf.get(a)},Sf=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]={};d[e[e.length-1]]=b;return c};var Uf=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Vf={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Wf={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Xf=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Yf=function(){var a=J("gtm.whitelist");
var b=a&&Xf(ff(a),Vf),c=J("gtm.blacklist")||J("tagTypeBlacklist")||[];Uf.test(H.location&&H.location.hostname)&&(c=ff(c),c.push("nonGooglePixels","nonGoogleScripts"));var d=c&&Xf(ff(c),Wf),e={};return function(f){var g=f&&f[Gc];if(!g)return!0;if(void 0!==e[g.a])return e[g.a];var h=!0;if(a)a:{if(0>df(b,g.a))if(g.b&&0<g.b.length)for(var k=0;k<g.b.length;k++){if(0>df(b,
g.b[k])){h=!1;break a}}else{h=!1;break a}h=!0}var m=!1;if(c){var l;if(!(l=0<=df(d,g.a)))a:{for(var n=g.b||[],q=new hf,t=0;t<d.length;t++)q.set(d[t],!0);for(t=0;t<n.length;t++)if(q.get(n[t])){l=!0;break a}l=!1}m=l}return e[g.a]=!h||m}};var tf=function(a){var b=R;return Zf?b.querySelectorAll(a):null},$f=!1;if(R.querySelectorAll)try{var ag=R.querySelectorAll(":root");ag&&1==ag.length&&ag[0]==R.documentElement&&($f=!0)}catch(a){}var Zf=$f;var _eu=function(a){var b=String(J("gtm.elementUrl")||a[bc]||""),c=xa(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return La};_e.a="e";_e.b=["google"];var fg=/(^|\.)doubleclick\.net$/i,gg=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,ia=function(a){for(var b=String(R.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=ef(e[0]);if(f&&f==a){var g=ef(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},hg=function(a,b,c,d,e){if(fg.test(R.location.hostname)||"/"==c&&gg.test(d))return!1;var f=a+"="+b+"; ";c&&(f+="path="+c+"; ");e&&(f+="expires="+e.toGMTString()+"; ");d&&(f+="domain="+d+";");var g=R.cookie;R.cookie=f;return g!=
R.cookie||0<=df(ia(a),b)},ig=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},jg=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},kg=function(){var a=Of(H.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var lg=function(a,b){this.f=a;this.j=b};lg.prototype.toString=function(){var a=""+this.f;1<this.j&&(a=a+"-"+this.j);return a};var mg=function(a,b){this.Ea=a;this.ea=b};mg.prototype.toString=function(){return""+this.ea+"."+this.Ea};var pg=function(a,b){var c=new ng(null,a,b);og(c);return c},ng=function(a,b,c){this.Na=Math.floor(I().getTime()/864E5);this.da=b||"auto";this.W=c||"/";var d=ig(this.da),e=jg(this.W);this.D=a||new lg(d,e);this.h=[];this.B=new hf},rg=function(a,b,c){b&&(""==c.Ea?qg(a,b):(a.B.contains(b)||a.h.push(b),a.B.set(b,c)))},sg=function(a,b){for(var c=0;c<b.length;c++)rg(a,b[c][0],b[c][1])},qg=function(a,b){var c=df(a.h,b);0<=c&&a.h.splice(c,1);a.B.set(b,void 0)},tg=function(a){for(var b=[],c=0;c<a.h.length;c++){var d=
a.h[c];b.push([d,a.B.get(d)])}return b},ug=function(a){for(var b=0,c=0;c<a.h.length;c++)b=Math.max(b,a.B.get(a.h[c]).ea);return 864E5*b};ng.prototype.toString=function(){if(0==this.h.length)return"";for(var a=[],b=0;b<this.h.length;b++){var c=this.h[b];a.push(""+c+"."+this.B.get(c).toString())}return"GAX1."+this.D.toString()+"."+a.join("!")};
var vg=function(a,b){for(var c=new Date,d=jg(a.W),e=[],f=0;f<a.h.length;f++){var g=a.h[f];a.B.get(g).ea<a.Na&&e.push(g)}for(f=0;f<e.length;f++)qg(a,e[f]);if(a.h.length>(b||10))return!1;c.setTime(ug(a));if("auto"!=a.da)return hg("_gaexp",a.toString(),a.W,a.da,c);for(var h=kg(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.D=new lg(ig(h[k]),d),hg("_gaexp",a.toString(),a.W,h[k],c)))return!0;return!1},og=function(a){for(var b=a.D.f,c=a.D.j,d=ia("_gaexp"),e=[],f=0;f<d.length;f++){var g=wg(a,d[f]);g&&e.push(g)}sf(e,
function(a,d){var e=a.D,f=d.D;return e.f==f.f&&e.j==f.j?!1:e.f==b&&e.j==c?!0:f.f==b&&f.j==c?!1:e.f==b?f.f!=b||e.j<f.j:f.f==b?!1:e.j==c?f.f!=b&&(f.j!=c||e.f<f.f):f.j==c?!1:e.f<f.f||e.f==f.f&&e.j<f.j});a.D=0<e.length?e[0].D:new lg(b,c);for(f=e.length-1;0<=f;f--)sg(a,tg(e[f]))},wg=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=ef(e[0]);if(0!=f.length){var g=2==e.length?ef(e[1]):"1";if(cf(f)&&cf(g)){d=new lg(O(f),O(g));
break a}}}d=void 0}if(d){for(var h=new ng(d,a.da,a.W),k=(c[2]||"").split("!"),m=0;m<k.length;m++){var l=k[m].split(".");if(3==l.length){if(!cf(l[1]))return;rg(h,l[0],new mg(l[2],O(l[1])))}}return h}}};var _f=function(a){var b=String(J("gtm.referrer")||R.referrer);if(!b)return b;var c=xa(b);return b};_f.a="f";_f.b=["google"];var ea=function(a){var b=H.location,c;(c=a[Rb]?a[Rb]:J("gtm.url"))&&(b=xa(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Bb]&&(f=Of(b,a[Bb],a[ee],a[ac],a[Sd]));return f},_u=ea;_u.a="u";_u.b=["google"];var _eq=function(a){return String(a[$a])==String(a[ab])};_eq.a="eq";_eq.b=["google"];var Kg=Math.random(),Lg="1.000000">Kg;var Mg=$e;var Ng=$e,Og=[],Pg=!1,Qg=function(a){return H["dataLayer"].push(a)},Rg=function(a){var b=!1;return function(){!b&&N(a)&&x(mf(a));b=!0}},Xg=function(){for(var a=!1;!Pg&&0<Og.length;){Pg=!0;var b=Og.shift();if(N(b))try{b.call(Tf)}catch(ua){}else if(af(b))a:{var c=b;if("string"==Fa(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=Rf,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(ua){}}}else{var k=b,m=void 0;for(m in k)if(k.hasOwnProperty(m)){var l=m,
n=k[m];Qf.set(l,n);Ha(Sf(l,n),Rf)}var q=!1,t=k.event,v=void 0;if(t){v=of++;La=t;if(!k["gtm.uniqueEventId"]){var w=v;Qf.set("gtm.uniqueEventId",w);Ha(Sf("gtm.uniqueEventId",w),Rf)}var A=Rg(k.eventCallback),D=k.eventTimeout;D&&H.setTimeout(A,Number(D));q=Ng(v,t,A,k.eventReporter)}Ka||(Ka=k["gtm.start"])&&Mg();var F=k,E=v,y=t,K=Rf;if(!q){var B=v,L=t;
}La=null;a=q||a}var S=b,P=Rf;Wg();Pg=!1}return!a},Yg=function(){var a=Xg();try{var b=H["dataLayer"].hide;if(b&&void 0!==b["GTM-WLGFZV"]&&b.end){b["GTM-WLGFZV"]=!1;var c=!0,d;for(d in b)if(!0===b[d]){c=!1;break}c&&(b.end(),
b.end=null)}}catch(e){}return a};var Zg,$g,ah,bh=/(Firefox\D28\D)/g.test(vf.userAgent),hh=function(a,b){return function(c){c=c||H.event;var d=If(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=Jf(d,["a","area"]),e=!d||!d.href||ch(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?ah:$g;if(c.defaultPrevented||!1===c.returnValue||c.sa&&c.sa()){if(d){var g={simulateDefault:!1},h=dh(f,["wnc","nwnc"]);h&&eh(a,d,g,f.wt,h)}}else{if(d){var g={},k,m=dh(f,
["wnc","nwnc","nwc","wc"]);(k=eh(a,d,g,f.wt,m))||(fh(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&bh;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=gh(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},eh=function(a,b,c,d,e){var f=d||2E3,g={"gtm.element":b,"gtm.elementClasses":b.className,"gtm.elementId":b["for"]||Gf(b,"id")||"","gtm.elementTarget":b.formTarget||b.target||""};switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event=
"gtm.linkClick";g["gtm.elementUrl"]=b.href;g.eventTimeout=f;g.eventCallback=ih(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=e||"";g.event="gtm.formSubmit";g["gtm.elementUrl"]=jh(b);g.eventTimeout=f;g.eventCallback=kh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";g["gtm.elementUrl"]=(b.attributes&&b.attributes.formaction?b.formAction:"")||b.action||b.href||b.src||b.code||b.codebase||"";break;default:return!0}return Qg(g)},
jh=function(a){var b=a.action;b&&b.tagName&&(b=a.cloneNode(!1).action);return b},lh=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},gh=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(vf.userAgent),e=lh(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);b.targetWindow=H.frames&&H.frames[f]||H[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName=
"gtm_autoEvent_"+I().getTime(),b.targetWindow=H.open("",b.targetWindowName));break;default:d&&!H.frames[e]?(b.simulateDefault=!1,c=!0):(H.frames[e]||(b.targetWindowName=e),b.targetWindow=H.frames[e]||H.open("",e))}return c},ih=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||I().getTime(),500>I().getTime()-c&&H.setTimeout(ih(a,b,c),25)))}},kh=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&
(d=a.target,a.target=b.targetWindowName);R.gtmSubmitFormNow=!0;mh(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||I().getTime(),500>I().getTime()-c&&H.setTimeout(kh(a,b,c),25)}},dh=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},nh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},fh=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;
for(var c=0;c<oh.length;c++)if(a.passingRules[c]){var d=ph[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=oh[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},qh=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(R.gtmHasClickListenerTag)return;R.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=If(a);b&&eh("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Zg&&(Zg=Pf(R.location));nh($g,b||!1,c||!1,d,e);if(R.gtmHasLinkClickListenerTag)return;
R.gtmHasLinkClickListenerTag=!0;f="click";g=hh(a,b||!1);break;case "FORM_SUBMIT":nh(ah,b||!1,c||!1,d,e);if(R.gtmHasFormSubmitListenerTag)return;R.gtmHasFormSubmitListenerTag=!0;f="submit";g=hh(a,b||!1);break;default:return}U(R,f,g,h)},ch=function(a){if(!Zg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=xa(a);return Zg==Pf(c)},mh=function(a){try{if(a.constructor&&a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;
R.gtmFormElementSubmitter||(R.gtmFormElementSubmitter=R.createElement("form"));return R.gtmFormElementSubmitter.submit.call?R.gtmFormElementSubmitter.submit:a.submit};var xg=new String("undefined"),yh=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===xg?b:a[d]);return c.join("")}};yh.prototype.toString=function(){return this.resolve("undefined")};yh.prototype.valueOf=yh.prototype.toString;var zh={},Ah=function(a,b){var c=of++;zh[c]=[a,b];return c},Bh=function(a){var b=a?0:1;return function(a){var d=zh[a];if(d&&N(d[b]))d[b]();zh[a]=void 0}};var Ch=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Dh=function(a,b){return a<b?-1:a>b?1:0};var Eh;a:{var Fh=Ba.navigator;if(Fh){var Gh=Fh.userAgent;if(Gh){Eh=Gh;break a}}Eh=""}var V=function(a){return-1!=Eh.indexOf(a)};var Hh=function(a){Hh[" "](a);return a};Hh[" "]=function(){};var Jh=function(a,b){var c=Ih;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Kh=V("Opera"),Lh=V("Trident")||V("MSIE"),Mh=V("Edge"),Nh;if(Nh=V("Gecko"))Nh=!(-1!=Eh.toLowerCase().indexOf("webkit")&&!V("Edge"));var Oh=Nh&&!(V("Trident")||V("MSIE"))&&!V("Edge"),Ph=-1!=Eh.toLowerCase().indexOf("webkit")&&!V("Edge");Ph&&V("Mobile");V("Macintosh");V("Windows");V("Linux")||V("CrOS");var Qh=Ba.navigator||null;Qh&&(Qh.appVersion||"").indexOf("X11");V("Android");!V("iPhone")||V("iPod")||V("iPad");V("iPad");V("iPod");
var Rh=function(){var a=Ba.document;return a?a.documentMode:void 0},Sh;a:{var Th="",Uh=function(){var a=Eh;if(Oh)return/rv\:([^\);]+)(\)|;)/.exec(a);if(Mh)return/Edge\/([\d\.]+)/.exec(a);if(Lh)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ph)return/WebKit\/(\S+)/.exec(a);if(Kh)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Uh&&(Th=Uh?Uh[1]:"");if(Lh){var Vh=Rh();if(null!=Vh&&Vh>parseFloat(Th)){Sh=String(Vh);break a}}Sh=Th}
var Wh=Sh,Ih={},Xh=function(a){return Jh(a,function(){for(var b=0,c=Ch(String(Wh)).split("."),d=Ch(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],m=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==m[0].length)break;b=Dh(0==k[1].length?0:parseInt(k[1],10),0==m[1].length?0:parseInt(m[1],10))||Dh(0==k[2].length,0==m[2].length)||Dh(k[2],m[2]);g=k[3];h=m[3]}while(0==b)}return 0<=b})},Yh=Ba.document,
Zh=Yh&&Lh?Rh()||("CSS1Compat"==Yh.compatMode?parseInt(Wh,10):5):void 0;var $h;if(!($h=!Oh&&!Lh)){var ai;if(ai=Lh)ai=9<=Number(Zh);$h=ai}$h||Oh&&Xh("1.9.1");Lh&&Xh("9");var va=function(a,b){var c="";Lh&&!bi(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(ci)a.srcdoc=d;else if(di){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else ei(a,d)},ci=Ph&&"srcdoc"in document.createElement("iframe"),di=Oh||Ph||Lh&&Xh(11),ei=function(a,b){Lh&&Xh(7)&&!Xh(10)&&6>fi()&&gi(b)&&(b=hi(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Lh&&!bi(a)?ii(a,c):c()},fi=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},bi=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Hh(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},ji=0,ii=function(a,b){var c="goog_rendering_callback"+ji++;window[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},gi=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},hi=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var zi=function(a,b,c,d){var e=b+": "+c+(d?" !important":""),f=document;if(f.createStyleSheet){var g=wi(f),h=g.rules.length;g.addRule(a,e);return function(){g.removeRule?g.removeRule(h):g.deleteRule(h);g.addRule("x","-",h)}}var k=xi(a+"{"+e+"}",f);yi(k,f);var m=k.parentNode;return function(){m.removeChild(k)}},Ai=null,wi=function(a){if(Ai)return Ai;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Ai=c}0==a.styleSheets.length&&
a.createStyleSheet();return Ai=a.styleSheets[0]},xi=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},yi=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Hi={},Ii=void 0,Ji=function(a){var b=Hi[a];b||(b={id:a,u:[],T:0,Ha:null,ya:void 0,Ca:!1},Hi[a]=b);Ii=b},Li=function(a,b,c,d){var e=Ii;if(!Zf||!e)return!1;var f={id:e.id+":"+e.u.length,eb:b,R:[],Za:c,F:a,qa:0,na:d||null,Ma:0,S:!1};e.u.push(f);null===a?(f.S=!0,b(null)):Ki(e);return!0},Mi=function(a){var b=zi(a,"visibility","hidden",!0);return function(){N(b)&&b.apply();b=null}},Ni=function(a,b,c,d){var e=b;if(!ra){var f=Mi(a.w);sa.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Li(a,e,
c,d)},Ki=function(a){if(!a.Ca){for(var b=a.T;b<a.u.length;b++){var c=a.u[b],d=b==a.T;if(!c.S&&!Oi(d,c))break;c.S&&d&&a.T++}a.u.length>a.T?(a.Ha||(a.Ha=H.setTimeout(function(){a.Ha=null;Ki(a)},80)),ra||a.ya||(a.ya=function(){x(function(){Ki(a)})},U(R,"DOMContentLoaded",a.ya))):Pi(a)}},Pi=function(a){for(var b=0;b<a.u.length;b++){var c=a.u[b];if(c.F)for(var d=tf(c.F.w)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Qi(f,c.id),c.R.push(Ri(f,c.id)))}}},Oi=
function(a,b){var c=[];if(b.F){var d=Si(b.F,b.id),e=null;b.na&&(e=Si(b.na,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!ra&&(null===b.na.o||b.Ma+c.length<b.na.o)))break;c.push({element:g,Lb:h})}}if(!ra&&b.Za&&(!a||null==b.F.o||b.F.o!=b.qa+c.length))return!1;for(var k=0;k<c.length;k++){var m=c[k].element,l=c[k].Lb,n;b.qa++;Qi(m,b.id);l&&(b.Ma++,n=b.id+"-t",Qi(l,n));var q=b.eb(m,l);N(q)&&b.R.push(q);b.R.push(Ri(m,b.id));l&&n&&b.R.push(Ri(l,n))}if(b.F.o&&
b.F.o==b.qa||ra)b.S=!0;return!0},Qi=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Ri=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Si=function(a,b){for(var c=tf(a.w)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.C&&!Ti(f))break;d.push(f)}}return d},Ti=function(a){if(ra)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Wi,Xi;var gj=function(a){return function(){}},hj=function(a){return function(){}};var Kj=function(a){var b=H||Ba,c=b.onerror,d=!1;Ph&&!Xh("535.3")&&(d=!d);b.onerror=function(b,f,g,h,k){c&&c(b,f,g,h,k);a({message:b,fileName:f,Cb:g,cc:h,error:k});return d}};var gk=26,hk=[],ik=[],jk=[],kk=new hf,lk=[],Y=[],oh=[],ph=[],mk=function(){this.I=[]};mk.prototype.set=function(a,b){this.I.push([a,b]);return this};mk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.I.length;d++){var e=nk(this.I[d][0],a,b),f=nk(this.I[d][1],a,b);c[e]=f}return c};var ok=function(a){this.index=a};ok.prototype.resolve=function(a,b){var c=jk[this.index];if(c&&!b(c)){var d=c[Rc];if(a){if(a.get(d))return;a.set(d,!0)}c=nk(c,a,b);a&&a.set(d,!1);return jf(c)}};
var _M=function(a){return new ok(a)},pk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=nk(hk[a[f]],b,c);g===xg&&(e=!0);d.push(g)}return e?new yh(d):d.join("")}},_T=function(a){return new pk(arguments)},qk=function(a){function b(b){for(var d=1;d<a.length;d++)if(a[d]==b)return!0;return!1}this.resolve=
function(c,d){var e=nk(a[0],c,d);if(a[0]instanceof ok&&b(8)&&b(16)){if(e===xg)return e;var f=ka();kk.set(f,e);return'google_tag_manager["GTM-WLGFZV"].macro(\''+f+"')"}for(var e=String(e),g=1;g<a.length;g++)e=X[a[g]](e);return e}},_E=function(a,b){return new qk(arguments)},rk=function(a,b){this.v=a;this.ma=b},_R=function(a,b){return new rk(a,b)},nk=function(a,b,c){var d=a;if(a instanceof ok||a instanceof mk||a instanceof pk||a instanceof qk)return a.resolve(b,c);if(!(a instanceof rk))if(af(a))for(var d=
[],e=0;e<a.length;e++)d[e]=nk(a[e],b,c);else if(a&&"object"==typeof a){var d={},f;for(f in a)a.hasOwnProperty(f)&&(d[f]=nk(a[f],b,c))}return d},sk=function(a,b){var c=b[a],d=c;if(c instanceof ok||c instanceof qk||c instanceof pk||c instanceof rk)d=c;else if(af(c))for(var d=[],e=0;e<c.length;e++)d[e]=sk(c[e],b);else if("object"==typeof c){var d=new mk,f;for(f in c)c.hasOwnProperty(f)&&d.set(b[f],sk(c[f],b))}return d},uk=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");
0==a&&(e[1]=hk[e[1]]);if(1==a)for(var f=tk(e[0]),e=c[d]={},g=0;g<f.length;g++){var h=ik[f[g]];e[h[0]]=h[1]}if(2==a)for(g=0;4>g;g++)e[g]=tk(e[g]);3==a&&(c[d]=hk[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=hk[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},tk=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<gk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:
62;1&f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},vk=function(a,b,c){a.push.apply(a,uk(b,c))};
var Tg=function(){},Dk=function(a){},Wg=function(){},Ek=function(a){},Fk=function(a,b){},Gk=function(a,b){},Ug=function(a){};var Hk=function(a){var b=this;this.g=a;this.complete=this.Va=!1;this.la=[];this.fa=[];this.O=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||nf(b.la);rf(b,1);if(Na[a])for(var e=0;e<Na[a].length;e++)Na[a].shift().O()};this.N=function(){if(b.s&&b.s.event){var c=b.s.event,d=b.g;}b.complete||
nf(b.fa);rf(b,2);if(Na[a])for(var e=0;e<Na[a].length;e++)Na[a].shift().N()};this.A=$e},Ik=function(a,b){a.la.push(b)},Jk=function(a,b){a.fa.push(b)},Kk=function(a){this.J=[];this.Fa=[];this.Oa={};this.wa=[];this.U=0;this.Ta={};this.Wa={};this.Ga={};this.event=a};Kk.prototype.addListener=function(a){this.wa.push(a)};
var Lk=function(a,b,c,d,e,f){if(!c.complete){a.J[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=af(d)?d.slice():["or",d];e=af(e)?e.slice():[e];f=af(f)?f.slice():[f];a.Oa[b]=d;a.Ta[b]=0<e.length;a.Wa[b]=0<f.length;a.U++;var g=function(){0<a.U&&a.U--;0<a.U||nf(a.wa)};Ik(c,g);Jk(c,g)}},Mk=function(a,b,c){a.J[b]&&(Ik(a.J[b],function(){c(b,!0)}),Jk(a.J[b],function(){c(b,!1)}))},Nk=function(a,b){var c=!1;return function(d,e){var f;a:{for(var g=0;g<a.length;g++)if(a[g]instanceof rk&&a[g].v===
d||a[g]===d){f=g;break a}f=-1}c||0>f||("or"==a[0]?e?(c=!0,b()):(a.splice(f,1),1==a.length&&(c=!0)):e?(a.splice(f,1),1==a.length&&(c=!0,b())):c=!0)}},Rk=function(a,b){var c=[],d=!1,e=function(b){var f,g,h=Y[b];if(a.event.c(h)){}else g=Ok(h,b,a);if(f=g){var k=Pk(b,!0);0<k.length&&e(k[0].v);c.push(f);var l=Pk(b,!1);0<l.length&&e(l[0].v)}else d=
!0};e(b);if(!d){for(var f=0;f<c.length;f++){var g=c[f],h=Pk(g.g,!0);if(0<h.length){var k=c[f-1],m=Qk(g);Ik(k,m);0==h[0].ma&&Jk(k,m)}var l=Pk(g.g,!1);0<l.length&&(m=Qk(c[f+1]),Ik(g,m),0==l[0].ma&&Jk(g,m))}a.Fa.push(c)}},Pk=function(a,b){var c=b?be:se,d=Y[a],e=void 0===d[c]?[]:d[c];return af(e)?e:[e]},Qk=function(a){return function(){a.A()}},Tk=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Pk(a,!0);0<b.length&&f(b[0].v);e.push(a);var c=Pk(a,!1);0<c.length&&f(c[0].v)};
f(d.g);b[d.g]=e}Sk(a,b);return b},Sk=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].g,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<df(b[e],d)){delete b[d];break}}};var Vk=function(a,b){return function(){a[Ic]=b.O;a[Jc]=b.N;var c=b.g,d=b.s&&b.s.Ga[c],e=Ma[c]&&Ma[c].state,f=d?void 0!==d:b.Va||b.dc,g=Ma[c]&&Ma[c].firingOption,h=g&&2==g,k=g&&1==g;if(!f&&void 0===e||!f&&!h||!h&&!k){rf(b,0);var m=b.s?b.s.event:void 0;a=Uk(a,m?m.c:Yf());if(m){var l=a;Fk(m,c)}jf(a,b.O,b.N)}else h&&0==e||k&&0==d?Na[c].push(b):h&&1==e||k&&1==d?b.O():b.N()}},Uk=function(a,b){a=nk(a,new hf,b);return a},Ok=function(a,b,c){var d=new Hk(b);d.s=c;Ik(d,gj(a));Jk(d,hj(a));d.A=Vk(a,d);return d};
var Zk=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];H[m()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!la(b))return!1;for(var e=ma(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[jc]?c=J("ecommerce"):
a[ic]&&(c=a[ic].ecommerce);if(!la(c))return;c=Object(c);var e=ma(a[Dc],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&v[e]||!c&&void 0===v[e])){var f=w[e]?ha(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}M("GoogleAnalyticsObject",a[md]||"ga",!1);var m=function(){return H.GoogleAnalyticsObject},l=M(m(),function(){var a=H[m()];a.q=a.q||[];a.q.push(arguments)},!1);l.l=Number(I());var n="",q="";"string"!=typeof a[Fe]?(q=ka(),n=q+"."):""!==
a[Fe]&&(q=a[Fe],n=q+".");var t=!1;
var A={name:q};l("create",a[Pa],A);d("set","&gtm","GTM-WLGFZV");var F;a[bd]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(N(a[Kc]))a[Kc]();else{var c=a[Dc],d=c&&c.hitCallback;N(d)&&d()}b()});if(a[Be]){}else if(a[Ce]){}else if(a[Ee]){}else if(a[De]){}else if(a[$b]){}else if(a[Yb]){}else if(a[Ae]){}else{a[rc]&&(d("require","ec","ec.js"),h());if(a[hc]&&!a[tc]){var P="_dc_gtm_"+String(a[Pa]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:P})}F?d("send","pageview",F):d("send","pageview");}if(!Zk){var W=a[Wb]?"u/analytics_debug.js":"analytics.js";a[Sc]&&!a[Wb]&&(W="internal/"+W);
Zk=!0;r(Q("https:","http:","//www.google-analytics.com/"+W,t),function(){H[m()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var $k,al;var jl=!1;var kl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=lk[b]&&nk(lk[b],new hf,c),e=d;if(d)if(d[Za]&&af(d[ab]))for(var f=d[ab],e=!1,g=0;!e&&g<f.length;g++)d[ab]=f[g],e=jf(d);else e=jf(d);a[b]=[e,d]}return a[b]}},Ck=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.M(c[d],a.c)[0])return!1;for(var e=b[2],d=0;d<e.length;d++)if(a.M(e[d],a.c)[0])return!1;return!0},ll=!1,Ng=function(a,b,c,d){switch(b){case "gtm.js":if(ll)return!1;ll=!0;break;case "gtm.sync":if(J("gtm.snippet")!=Ja)return!1}J("tagTypeBlacklist");
for(var e={id:a,name:b,ba:c||$e,aa:tk(),ka:tk(),M:kl(),c:Yf()},f=[],g=0;g<oh.length;g++)if(Ck(e,oh[g])){f[g]=!0;for(var h=e,k=oh[g],m=k[1],l=0;l<m.length;l++)h.aa[m[l]]=!0;for(var n=k[3],l=0;l<n.length;l++)h.ka[n[l]]=!0}else f[g]=!1;Fk(e);var t=[];for(var v=0;v<gk;v++)if(e.aa[v]&&!e.ka[v])if(e.c(Y[v])){}else{t[v]=Y[v];}e.P=t;for(var w=new Kk(e),A=0;A<gk;A++)if(e.aa[A]&&!e.ka[A])if(e.c(Y[A])){}else{var D=e.P[A],F=Ok(D,A,w);Lk(w,A,F,D[cc],D[be],D[se]);if(D[Oa])break}w.addListener(e.ba);for(var E=[],
y=0;y<w.J.length;y++){var K=w.J[y];if(K){var z=w.Oa[y],B=w.Ta[y],L=w.Wa[y];if(0!=z.length||B||L){if(0<z.length)for(var S=Nk(z,K.A),P=0;P<z.length;P++)z[P]instanceof rk&&z[P].v!=y&&Mk(w,z[P].v,S);(B||L)&&Rk(w,y)}else E.push(y)}}for(y=0;y<E.length;y++)w.J[E[y]].A();for(y=0;y<w.Fa.length;y++){for(var ua=w.Fa[y],W=ua,ja=[],fa=0;fa<W.length;fa++){var pb=W[fa],nb=pb.g,Mb=Ma[nb],rd=Mb.firingOption;0!=rd&&(1==rd&&void 0!==pb.s.Ga[nb]||2==rd&&void 0!==Mb.state)&&ja.push(pb)}var sd=Tk(ja),wc=void 0;for(wc in sd)if(sd.hasOwnProperty(wc)){for(var yf=
void 0,nj=void 0,od=sd[wc],yl=od[0],uj=od[od.length-1],vj,Ia=0;Ia<W.length;Ia++){var pd=W[Ia];!yf&&pd.g==yl&&0<Ia&&(yf=W[Ia-1]);pd.g==uj&&Ia<W.length-1&&(nj=W[Ia+1]);if(-1<df(od,pd.g))if(vj=W.splice(Ia,1)[0],pd.g==uj)break;else Ia--}if(vj){var wj=Number(wc),na=yf,zf=nj;if(na){var zl=na.la[0],Al=na.fa[0],xj=na;xj.la=[];xj.fa=[];Ik(na,zl);Jk(na,Al)}if(na&&zf){var Af=Qk(zf);Ik(na,Af);var Bf=Pk(na.g,!1);0<Bf.length&&Bf[0].v!=wj&&0==Bf[0].ma&&Jk(na,Af);var Cf=Pk(zf.g,!0);0<Cf.length&&Cf[0].v!=wj&&0==Cf[0].ma&&
Jk(na,Af)}}}0<ua.length&&ua[0].A()}0<w.U||nf(w.wa);d&&N(d)&&d({passingRules:f,resolvedTags:e.P});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var Aj in e.P)if(e.P.hasOwnProperty(Aj)){var Bj=e.P[Aj],Df;if(!(Df=void 0==Bj[Rc])){var Cj=Bj[Rc];Df=!("function"!=typeof String.prototype.startsWith?0===Cj.indexOf("_implicit"):Cj.startsWith("_implicit"))}if(Df)return!0}return!1};var ml={macro:function(a){if(kk.contains(a))return kk.get(a)}};ml.dataLayer=Tf;ml.onHtmlSuccess=Bh(!0);ml.onHtmlFailure=Bh(!1);ml.callback=function(a){za.hasOwnProperty(a)&&N(za[a])&&za[a]();delete za[a]};ml.jb=function(){var a=H.google_tag_manager;a||(a=H.google_tag_manager={});a["GTM-WLGFZV"]||(a["GTM-WLGFZV"]=ml);pa=a};(function(){var a=function(a){var c=M("google_tag_manager",{},!1),d=c[a];d||(d=c[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};$g=a("linkClickMap");ah=a("formSubmitMap")})();
hk.push.apply(hk,function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','2275454_2147479553',_ua,true,'UA-6096819-11',false,'\x26tid',{10:8},1,_u,'Page URL','Page Hostname','host','Page Path','path',_f,'Referrer','Event'],b=[],c=0;c<a.length;c++)b[c]=sk(c,a);return b}());vk(ik,0,"10:0,10:1,11:2,2:3,3:4,10:6,13:7,0:8,9:9,8:9,15:9,5:9,6:9,1:11,12:9,7:9,14:12,10:13,11:14,11:15,4:16,11:17,4:18,10:19,11:20,11:21");vk(jk,1,"G,AAgB,AAgG,AAgY,AAAgB,CAAAC");vk(lk,1,"Z");vk(Y,1,"g_f");vk(oh,2,"B:B::");vk(ph,4,"5:");for(var nl=0;nl<Y.length;nl++){var ol=Y[nl],pl=1;ol[xd]?pl=2:ol[Le]&&(pl=0);Ma[nl]={firingOption:pl,state:void 0};Na[nl]=[]}ml.jb();
(function(a){})("async");
(function(){var a=M("dataLayer",[],!1),b=M("google_tag_manager",{},!1),b=b["dataLayer"]=b["dataLayer"]||{};sa.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});Lf.push(function(){b.gtmLoad||(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Og.push.apply(Og,b);300<this.length;)this.shift();return Xg()};Og.push.apply(Og,a.slice(0));x(Yg)})();
if("interactive"==R.readyState&&!R.createEventObject||"complete"==R.readyState)xf();else{U(R,"DOMContentLoaded",xf);U(R,"readystatechange",xf);if(R.createEventObject&&R.documentElement.doScroll){var xl=!0;try{xl=!H.frameElement}catch(a){}xl&&Ff()}U(H,"load",xf)}"complete"===R.readyState?Mf():U(H,"load",Mf);
(function(a){})("async");(function(){})();var _vs="res_ts:1464731784677000,srv_cl:130124299,ds:live,cv:1";
})()
