---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-name: '@docker/marlin-sdk-web-public'
    open-pull-requests-limit: 1

  - package-ecosystem: gomod
    directory: /
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: '*'
    schedule:
      interval: weekly
