services:
  server:
    build:
      context: .
      target: build-base
    volumes:
      - "${PWD}:/src"
      - /src/node_modules
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
