services:
  server:
    build:
      context: .
      target: build-base
    ports:
      - "1313:1313"
    entrypoint: ["hugo", "server", "--bind", "0.0.0.0"]
    develop:
      watch:
        - action: sync
          path: .
          target: /project
          ignore:
            - hack/api-docs/
            - content/reference/api/hub/latest.yaml
            - content/reference/api/dvp/latest.yaml
            - content/reference/api/registry/latest.yaml
        - action: rebuild
          path: hack/api-docs
        - action: rebuild
          path: content/reference/api/hub/latest.yaml
        - action: rebuild
          path: content/reference/api/dvp/latest.yaml
        - action: rebuild
          path: content/reference/api/registry/latest.yaml
