#!/bin/bash

# match the ip address from a DOCKER_HOST which is set by boot2docker
# and docker-machine
if [[ $DOCKER_HOST =~ ([0-9]{1,3}[\.]){3}[0-9]{1,3} ]]; then
    strresult=$BASH_REMATCH
    echo $strresult
else
    echo "unable to parse string $DOCKER_HOST"
fi

/usr/sbin/dnsmasq -q --no-daemon --address=/bagels.docker.com/$strresult
#$strresult
