command: docker compose ps
short: List containers
long: |-
  Lists containers for a Compose project, with current status and exposed ports.

  ```console
  $ docker compose ps
  NAME                SERVICE             STATUS              PORTS
  example_foo_1       foo                 running (healthy)   0.0.0.0:8000->80/tcp
  example_bar_1       bar                 exited (1)
  ```
usage: docker compose ps [SERVICE...]
pname: docker compose
plink: docker_compose.yaml
options:
- option: all
  shorthand: a
  value_type: bool
  default_value: "false"
  description: |
    Show all stopped containers (including those created by the run command)
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: filter
  value_type: string
  description: Filter services by a property
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: format
  value_type: string
  default_value: pretty
  description: 'Format the output. Values: [pretty | json]'
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: quiet
  shorthand: q
  value_type: bool
  default_value: "false"
  description: Only display IDs
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: services
  value_type: bool
  default_value: "false"
  description: Display services
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: status
  value_type: string
  description: Filter services by status
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

