command: docker compose build
short: Build or rebuild services
long: |-
  Services are built once and then tagged, by default as `project_service`.

  If the Compose file specifies an
  [image](https://github.com/compose-spec/compose-spec/blob/master/spec.md#image) name,
  the image is tagged with that name, substituting any variables beforehand. See
  [variable interpolation](https://github.com/compose-spec/compose-spec/blob/master/spec.md#interpolation).

  If you change a service's `Dockerfile` or the contents of its build directory,
  run `docker compose build` to rebuild it.
usage: docker compose build [SERVICE...]
pname: docker compose
plink: docker_compose.yaml
options:
- option: build-arg
  value_type: stringArray
  default_value: '[]'
  description: Set build-time variables for services.
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: compress
  value_type: bool
  default_value: "true"
  description: Compress the build context using gzip. DEPRECATED
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: force-rm
  value_type: bool
  default_value: "true"
  description: Always remove intermediate containers. DEPRECATED
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: memory
  shorthand: m
  value_type: string
  description: |
    Set memory limit for the build container. Not supported on buildkit yet.
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: no-cache
  value_type: bool
  default_value: "false"
  description: Do not use cache when building the image
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: no-rm
  value_type: bool
  default_value: "false"
  description: |
    Do not remove intermediate containers after a successful build. DEPRECATED
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: parallel
  value_type: bool
  default_value: "true"
  description: Build images in parallel. DEPRECATED
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: progress
  value_type: string
  default_value: auto
  description: Set type of progress output ("auto", "plain", "noTty")
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: pull
  value_type: bool
  default_value: "false"
  description: Always attempt to pull a newer version of the image.
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: quiet
  shorthand: q
  value_type: bool
  default_value: "false"
  description: Don't print anything to STDOUT
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

