command: docker compose restart
short: Restart containers
long: Restart containers
usage: docker compose restart
pname: docker compose
plink: docker_compose.yaml
options:
- option: timeout
  shorthand: t
  value_type: int
  default_value: "10"
  description: Specify a shutdown timeout in seconds
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

