command: docker compose top
short: Display the running processes
long: Displays the running processes.
usage: docker compose top [SERVICES...]
pname: docker compose
plink: docker_compose.yaml
examples: |-
  ```console
  $ docker compose top
  example_foo_1
  UID    PID      PPID     C    STIME   TTY   TIME       CMD
  root   142353   142331   2    15:33   ?     00:00:00   ping localhost -c 5
  ```
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

