command: docker compose push
short: Push service images
long: |-
  Pushes images for services to their respective registry/repository.

  The following assumptions are made:
  - You are pushing an image you have built locally
  - You have access to the build key

  Examples

  ```yaml
  services:
    service1:
      build: .
      image: localhost:5000/yourimage  ## goes to local registry

    service2:
      build: .
      image: your-dockerid/yourimage  ## goes to your repository on Docker Hub
  ```
usage: docker compose push [SERVICE...]
pname: docker compose
plink: docker_compose.yaml
options:
- option: ignore-push-failures
  value_type: bool
  default_value: "false"
  description: Push what it can and ignores images with push failures
  deprecated: false
  hidden: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

