command: docker compose stop
short: Stop services
long: |
  Stops running containers without removing them. They can be started again with `docker compose start`.
usage: docker compose stop [SERVICE...]
pname: docker compose
plink: docker_compose.yaml
options:
- option: timeout
  shorthand: t
  value_type: int
  default_value: "10"
  description: Specify a shutdown timeout in seconds
  deprecated: false
  hidden: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
deprecated: false
experimental: false
experimentalcli: false
kubernetes: false
swarm: false

