#! /usr/bin/env python
#
# Copyright (C) 2016 Rolf Neugebauer <rolf.neugebauer@docker.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#

"""Run the Regression Tests on a (remote) host"""

import os
import sys

# add modules to the search path
sys.path.append(os.getcwd() + "/lib/python")

import rt.host
ret = rt.host.main()
sys.exit(ret)
