command: docker config create
short: Create a config from a file or STDIN
long: |-
  Creates a config using standard input or from a file for the config content.

  For detailed information about using configs, refer to [store configuration data using Docker Configs](https://docs.docker.com/engine/swarm/configs/).

  > **Note**
  >
  > This is a cluster management command, and must be executed on a swarm
  > manager node. To learn about managers and workers, refer to the
  > [Swarm mode section](https://docs.docker.com/engine/swarm/) in the
  > documentation.
usage: docker config create [OPTIONS] CONFIG file|-
pname: docker config
plink: docker_config.yaml
options:
- option: label
  shorthand: l
  value_type: list
  description: Config labels
  deprecated: false
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
- option: template-driver
  value_type: string
  description: Template driver
  deprecated: false
  min_api_version: "1.37"
  experimental: false
  experimentalcli: false
  kubernetes: false
  swarm: false
examples: |-
  ### Create a config

  ```console
  $ printf <config> | docker config create my_config -

  onakdyv307se2tl7nl20anokv

  $ docker config ls

  ID                          NAME                CREATED             UPDATED
  onakdyv307se2tl7nl20anokv   my_config           6 seconds ago       6 seconds ago
  ```

  ### Create a config with a file

  ```console
  $ docker config create my_config ./config.json

  dg426haahpi5ezmkkj5kyl3sn

  $ docker config ls

  ID                          NAME                CREATED             UPDATED
  dg426haahpi5ezmkkj5kyl3sn   my_config           7 seconds ago       7 seconds ago
  ```

  ### Create a config with labels

  ```console
  $ docker config create \
      --label env=dev \
      --label rev=20170324 \
      my_config ./config.json

  eo7jnzguqgtpdah3cm5srfb97
  ```

  ```console
  $ docker config inspect my_config

  [
      {
          "ID": "eo7jnzguqgtpdah3cm5srfb97",
          "Version": {
              "Index": 17
          },
          "CreatedAt": "2017-03-24T08:15:09.735271783Z",
          "UpdatedAt": "2017-03-24T08:15:09.735271783Z",
          "Spec": {
              "Name": "my_config",
              "Labels": {
                  "env": "dev",
                  "rev": "20170324"
              },
              "Data": "aGVsbG8K"
          }
      }
  ]
  ```
deprecated: false
min_api_version: "1.30"
experimental: false
experimentalcli: false
kubernetes: false
swarm: true

