// Automatically generated by MockGen. DO NOT EDIT!
// Source: io (interfaces: Closer)

package jobrunner

import (
	gomock "github.com/vikstrous/mock/gomock"
)

// Mock of Closer interface
type MockCloser struct {
	ctrl     *gomock.Controller
	recorder *_MockCloserRecorder
}

// Recorder for MockCloser (not exported)
type _MockCloserRecorder struct {
	mock *MockCloser
}

func NewMockCloser(ctrl *gomock.Controller) *MockCloser {
	mock := &MockCloser{ctrl: ctrl}
	mock.recorder = &_MockCloserRecorder{mock}
	return mock
}

func (_m *MockCloser) EXPECT() *_MockCloserRecorder {
	return _m.recorder
}

func (_m *MockCloser) Close() error {
	ret := _m.ctrl.Call(_m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockCloserRecorder) Close() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Close")
}
