FROM alpine:latest
MAINTAINER Anil Madhavapeddy <anil@docker.com>
RUN \
	mkdir -p /aws && \
	apk -Uuv add groff less python py-pip && \
	pip install awscli && \
	apk --purge -v del py-pip && \
	rm /var/cache/apk/*
WORKDIR /aws
ENTRYPOINT ["aws"]
