#!/bin/bash

# match the ip address from a DOCKER_HOST which is set by boot2docker
# and docker-machine
if [[ $DOCKER_HOST =~ ([0-9]{1,3}[\.]){3}[0-9]{1,3} ]]; then
    strresult=$BASH_REMATCH
    echo $strresult
else
    echo "unable to parse string $DOCKER_HOST"
fi

sed -i s/{DOCKER_HOST}/"$strresult"/g /haproxy/haproxy.cfg

# Check is haproxy.cfg is valid before we start
haproxy -c -f /haproxy/haproxy.cfg || ( echo 'Bad haproxy config'; exit; )

/usr/sbin/haproxy -f /haproxy/haproxy.cfg &

wait $!
