extends: existence
message: "Consider removing '%s'."
ignorecase: true
level: warning
tokens:
  - amazing
  - easily
  - game-changing
  - 'just(?!-in-time)'
  - please
  - powerful
  - really
  - revolutionary
  - robust
  - seamlessly
  - simply
  - very
