#!/bin/sh

set -e

docker build -t windows-installer -f Dockerfile.windows .
CONTAINER="$(docker run -d windows-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/installer/Output/DockerToolbox.exe dist/
docker rm "${CONTAINER}" 2>/dev/null || true
