#!/bin/bash

set -e

source $(dirname $0)/.build_utils


echo "Creating controller machine"
NODE=${PREFIX}-cluster-controller
if ! docker-machine ip ${NODE} > /dev/null ; then
    echo "Creating node ${NODE}"
    docker-machine create --driver amazonec2 \
        --amazonec2-request-spot-instance --amazonec2-spot-price ${SPOT_PRICE} \
        --amazonec2-instance-type ${INSTANCE_TYPE} --amazonec2-ami ${AMI} \
        --engine-install-url "https://get.docker.com" \
        --amazonec2-ssh-user admin ${EXTRA_MACHINE_FLAGS} \
        "${NODE}"
else
    echo "${NODE} already exists, using it"
fi

# Wire up the environment
eval "$(docker-machine env ${PREFIX}-cluster-controller)"

# TODO - might be nice to use the new pull command once it's merged...


echo ""
echo "Pre-Loading the required images"
for i in $(docker run --rm ${ORG}/ucp images --list --image-version ${TAG}); do
    docker pull $i
done

echo ""
echo "Deploying the controller"
NODE_IP=$(docker-machine ip ${NODE})
docker run --rm \
    --name ucp \
    -e UCP_ADMIN_PASSWORD \
    -e REGISTRY_USERNAME \
    -e REGISTRY_PASSWORD \
    -e REGISTRY_EMAIL \
    -v /var/run/docker.sock:/var/run/docker.sock \
    ${ORG}/ucp \
    install --san ${NODE_IP} --swarm-port 3376 --image-version ${TAG}

URL="https://${NODE_IP}/"
echo "The ACTUAL connection URL is ${URL}"
