#!/bin/bash

docker build -t osx-installer -f Dockerfile.osx .
CONTAINER="$(docker run -d osx-installer)"
mkdir -p dist
docker cp "${CONTAINER}":/DockerToolbox.pkg dist/
docker rm "${CONTAINER}" 2>/dev/null || true
