#!/bin/bash

# Copy the local images to the target system via machine's TLS docker remote API

set -e

if [ -z "$ORG" ]; then
    ORG=docker
fi

if [ "$ORG" = "dockerorcadev" ]; then
    IMAGE_VERSION_FLAGS="--image-version dev:"
fi

MACHINE_ENV=$(docker-machine env $1)

if [ -z "$TAG" ]; then
    _DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    TAG=$(cd ${_DIR}/..; make print-TAG)
    echo "Copying images using TAG=${TAG}"
fi
TRANSFER_IMAGES=""
for image in ${ORG}/ucp:${TAG} $(docker run --rm ${ORG}/ucp:${TAG} images ${IMAGE_VERSION_FLAGS} --list) ; do
    # Check to see if the image ID's match
    OUR_ID=$(docker inspect ${image}|jq -r ".[].Id")
    REMOTE_ID=$( (eval "${MACHINE_ENV}" ; docker inspect ${image} 2>/dev/null ) |jq -r ".[].Id")
    if [ "${OUR_ID}" != "${REMOTE_ID}" ] ; then
        TRANSFER_IMAGES="${TRANSFER_IMAGES} ${image}"
    else
        echo "Image ${image} already in sync"
    fi
done
if [ -n "${TRANSFER_IMAGES}" ] ; then
    echo "Migrating ${TRANSFER_IMAGES} to $1..."
    docker save ${TRANSFER_IMAGES} | (eval "${MACHINE_ENV}" ; docker load)
fi
