#!/bin/bash

# Copy a local images to the target orca system

# Expand your orca bundle here...
ORCA_CERTS=${HOME}/.docker/orca/certs

ENV_FILE=env.sh

echo "Copying $1 to $(grep DOCKER_HOST ${ORCA_CERTS}/${ENV_FILE}| cut -f2 -d=)"
time docker save $1 | (cd ${ORCA_CERTS} && source ${ENV_FILE} && docker load)
