FROM alpine:3.4

RUN \
    apk add --update \
        ca-certificates libstdc++ libgcc libcurl protobuf && \
    apk add --update \
        -X http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        libexecinfo

COPY rethinkdb /usr/local/bin/rethinkdb
USER nobody
ENTRYPOINT ["rethinkdb"]
