extends: existence
message: "Always spell out the name of the month."
link: https://deploy-preview-15350--docsdocker.netlify.app/contribute/style/grammar/#dates
ignorecase: true
level: error
nonword: true
tokens:
  - '\b\d{1,2}/\d{1,2}/(?:\d{4}|\d{2})\b'
