# Checks that a callout block is followed by a liquid tag
# (Doesn't actually check that there is a well-formed liquid
# tag, just checks that it is not an empty line.)
extends: existence
message: "Use a liquid tag for 'Important' or 'Warning' callouts."
link: https://docs.docker.com/contribute/components/call-outs/
level: warning
nonword: true
scope: raw
raw:
  - '[:blank:]*\>.*?'
  - "(?i)(?:important|warning|danger|caution)(?-i)"
  - '.*\n'
  - '(?:\s*\>.*?\n)+?'
  - '\s*\n'
