extends: existence
message: "Indent nested code blocks by 3 spaces and double-nested code blocks by 5 spaces."
link: https://docs.docker.com/contribute/style/formatting/#best-practice-for-commands
level: warning
scope: raw
# check for 1, 2, 4, 6 or more spaces at start of line before code fence (```)
# If not indented by 3 spaces at first level or 5 spaces at second level, then a hidden space is inserted and copied by the copy code feature.
raw:
  - '(?m:^[ ]{1}\`\`\`)|'
  - '(?m:^[ ]{2}\`\`\`)|'
  - '(?m:^[ ]{4}\`\`\`)|'
  - '(?m:^[ ]{6,}\`\`\`)'