extends: substitution
message: "Use '%s' instead of '%s'"
link: https://docs.docker.com/contribute/style/recommended-words/
level: error
swap:
  (?:kilobytes?|KB): kB
  gigabytes?: GB
  megabytes?: MB
  petabytes?: PB
  terrabytes?: TB
