'use strict';

import React, { Component } from 'react';
import Card, { Block } from '@dux/element-card';
import { PageHeader } from 'dux';
import styles from './EnterpriseTrialTerms.css';

export default class extends Component {
  render() {
    return (
    <div>
      <PageHeader title='Trial Software Agreement' />
      <div className={'row ' + styles.termsPageWrapper}>
        <div className='small-12 columns small-centered'>
          <Card>
            <Block>
              <div className={styles.softwareAgreement}>
                <p>This Docker software evaluation agreement("agreement") is by and between Docker Inc., located at 144 Townsend St, San Francisco, CA 94107("Docker") and the individual or legal entity who has executed an order form(or other ordering or purchasing document) referencing this agreement or is using the applicable software made available by Docker("customer") and governs all use by customer of the Docker software referenced in such order form. by executing an order form, customer expressly accepts and agrees to the terms of this agreement.if you are an individual agreeing to the terms of this agreement on behalf of an entity, such as your employer, you represent that you have the legal authority to bind that entity and "customer" shall refer herein to such entity.if you do not have such authority, or if you do not agree with the terms of this agreement, you must not execute the order form and may not use the licensed software(each as defined below). this agreement does not provide a commercial license after the trial period.use after the trial period is subject to the parties entering into and executing a separate written agreement.</p>
                <h5>1. Definitions.</h5>
                <p>The following capitalized terms shall have the meanings set forth below:</p>
                <h5>1.1 Feedback</h5>
                <p>"Feedback" means any comments or other feedback Customer may provide to Docker concerning the functionality and performance of the Licensed Software, including identification of potential errors and improvements.</p>
                <h5>1.2 Instance</h5>
                <p>"Instance" means a single instance of Licensed Software, as applicable, installed on a physical or virtual computer or server.</p>
                <h5>1.3 Key</h5>
                <p>Key means the license key or similar control mechanism to help ensure compliance with the use and time limitations with respect to the Licensed Software.</p>
                <h5>1.4 Licensed Software</h5>
                <p>Licensed Software means the Docker software identified on an Order Form (other than Open Source Software) and licensed to Customer pursuant to the terms of this Agreement, e.g., the "Docker trusted registry" software or other licensed software from Docker that is identified on the Order Form (excluding any Open Source Software included therein).</p>
                <h5>1.5 Open Source Software</h5>
                <p>Open Source Software means Docker or third party software identified at
                  <a href='https://www.Docker.com/components-licenses'> Docker.com/components-licenses,</a> that is distributed or otherwise made available as "free software",  "open source software" or under a similar licensing or distribution model.</p>
                <h5>1.6 Order Form</h5>
                <p>Order Form means an ordering document referencing this Agreement between Customer and Docker</p>
                <h5>1.7 Trial Period</h5>
                <p>"Trial Period" means 30 days</p>
                <h5>2. License.</h5>
                <h5>2.1 Licensed Software.</h5>
                <p>Licensed Software. Subject to Customer's compliance with the terms and conditions of this Agreement, Docker hereby grants Customer a limited, non-exclusive, non-transferable, non-sub-licensable license during the Trial Period to install, copy and use the Licensed Software solely for Customer's internal evaluation purposes, in connection with the deployment of no more than one Instance.</p>
                <h5>2.2 Open Source Software.</h5>
                <p>If applicable, Open Source Software is distributed or made available under the terms of the open source license agreements referenced in the applicable distribution or the applicable help, notices, about or source files. Copyrights and other proprietary rights to the Open Source Software are held by the copyright holders identified in the applicable distribution or the applicable help, notices, about or source files.</p>
                <h5>2.3 License Keys.</h5>
                <p>Customer shall not destroy, disable or circumvent, or attempt to destroy, disable or circumvent in any way the Key and/or the use and time limitations set by the Key or the Licensed Software. Customer acknowledges and agrees that any attempt to exceed the use of the Licensed Software beyond the limits configured into the Key will automatically and immediately terminate the licenses granted under this Agreement.</p>
                <h5>3. Payment.</h5>
                <p>Subject to Customer's compliance with the terms and conditions of this Agreement, and solely during the Trial Period, the Licensed Software shall be provided to Customer free of charge.</p>
                <h5>4. Restricted Activities.</h5>
                <p>Customer shall not, and shall not encourage any third party to: (a) modify, adapt, alter, translate, or create derivative works of the Licensed Software; (b) reverse-engineer, decompile, disassemble, or attempt to derive the source code for the Licensed Software, in whole or in part, except to the extent that such activities are permitted under applicable law; (c) distribute, license, sublicense, lease, rent, loan, or otherwise transfer the Licensed Software to any third party; (d) remove, alter, or obscure in any way the proprietary rights notices (including copyright, patent, and trademark notices and symbols) of Docker or its suppliers contained on or within any copies of the Licensed Software; (e) use the Licensed Software for the purpose of creating a product or service competitive with the Licensed Software; (f) use the Licensed Software with any unsupported software or hardware (as described in the applicable documentation provided by Docker); (g) use the Licensed Software for any time-sharing, outsourcing, service bureau, hosting, application service provider or like purposes; (h) disclose the results of any benchmark tests on the Licensed Software without Docker's prior written consent; or (i) use the Licensed Software other than as described in the documentation provided therewith, or for any unlawful purpose.</p>
                <h5>5. Ownership of Licensed Software.</h5>
                <p>Docker and its licensors own and retain all right, title, and interest, including all intellectual property rights, in and to the Licensed Software, including any improvements, modifications, and enhancements to it. Except for the rights expressly granted in this Agreement, Customer shall acquire no other rights, express or implied, in or to the Licensed Software, and all rights not expressly provided to Customer hereunder are reserved by Docker and its licensors. All the copies of the Licensed Software provided or made available hereunder are licensed, not sold.</p>
                <h5>6. Term.</h5>
                <p>Unless otherwise terminated in accordance with this section, this Agreement will remain in effect until the expiration of the Trial Period. Either party may immediately terminate this Agreement and any Order Form incorporating the terms of this Agreement if the other party materially breaches this Agreement. Either party may terminate this agreement without cause upon 10 days' prior written notice. Unless otherwise agreed by the parties, upon the expiration or termination of the Trial Period all licenses granted herein will automatically terminate and Customer will discontinue all use of the applicable Licensed Software and will return to Docker any materials (including any copies of Licensed Software) provided by Docker to Customer. Sections 1, 2.2, 4, 5, and 7 through 14 shall survive any termination or expiration of this Agreement or any Order Form.</p>
                <h5>7.Feedback.</h5>
                <p>Customer may submit to Docker bug reports, comments, feedback or ideas about the Licensed Software, including without limitation about how to improve the Licensed Software. By submitting any Feedback, Customer hereby assigns to Docker all right, title, and interest in and to the Feedback, if any.</p>
                <h5>8. Confidentiality.</h5>
                <h5>8.1 Definition.</h5>
                <p>"Confidential Information" means any information disclosed by one party ("Discloser") to the other ("Recipient"), directly or indirectly, in writing, orally or by inspection of tangible objects, which is designated as "Confidential," "Proprietary" or some similar designation, or learned by Recipient under circumstances in which such information would reasonably be understood to be confidential. Confidential Information may include information disclosed in confidence to Discloser by third parties. For the purposes of this Agreement, the Licensed Software, and the results of any performance, functional or other evaluation of the Licensed Software, shall be deemed Confidential Information of Docker.</p>
                <h5>8.2 Exceptions.</h5>
                <p>The confidentiality obligations in this Section 8 shall not apply with respect to any of the Discloser's Confidential information which Recipient can demonstrate: (a) was in the public domain at the time it was disclosed to Recipient or has become in the public domain through no act or omission of Recipient; (b) was known to Recipient, without restriction, at the time of disclosure as shown by the files of Recipient in existence at the time of disclosure; (c) was disclosed by Recipient with the prior written approval of Discloser; (d) was independently developed by Recipient without any use of Discloser's Confidential Information by employees or other agents of (or contractors hired by) Recipient who had no access to or did not rely on Discloser's Confidential Information; or (e) became known to Recipient, without restriction, from a source other than Discloser without breach of this Agreement by Recipient and otherwise not in violation of Discloser's rights.</p>
                <h5>8.3 Restrictions on Use and Disclosure.</h5>
                <p>Recipient agrees not to use Discloser's Confidential Information or disclose, distribute or disseminate Discloser's Confidential Information except in furtherance of the performance of its obligations or enforcement of its rights hereunder or as otherwise expressly agreed by Discloser in writing. Recipient agrees to restrict access to such Confidential Information to those employees or consultants of Recipient who need to know such Confidential Information for performing as contemplated hereunder and have agreed in writing to be bound by a confidentiality obligation no less protective than that contained in this Agreement. Recipient shall exercise the same degree of care to prevent unauthorized use or disclosure of Discloser's Confidential Information to others as it takes to preserve and safeguard its own information of like importance, but in no event less than reasonable care.</p>
                <h5>8.4 Compelled Disclosure.</h5>
                <p>If Recipient is compelled by a court or other competent authority or applicable law to disclose Confidential Information of Discloser, it shall give Discloser prompt written notice and shall provide Discloser with reasonable cooperation at Discloser's expense so that Discloser may take steps to oppose such disclosure or obtain a restraining order. Recipient shall not be in breach of its obligations in this Section 9 if it makes any legally compelled disclosure provided that Recipient meets the foregoing notice and cooperation requirements.</p>
                <h5>8.5 Injunctive Relief.</h5>
                <p>Recipient acknowledges that breach of the confidentiality obligations would cause irreparable harm to Discloser, the extent of which may be difficult to ascertain. Accordingly, Recipient agrees that Discloser is entitled to immediate injunctive relief in the event of breach of an obligation of confidentiality by Recipient, and that Discloser shall not be required to post a bond or show irreparable harm in order to obtain such injunctive relief.</p>
                <h5>8.6 Return of Confidential Information.</h5>
                <p>As between the parties, Confidential Information shall remain the property of the Discloser. At any time, upon Discloser's reasonable request, Recipient shall promptly (and in any event within 30 days) return to Discloser or destroy, at the election of the Discloser, any Confidential Information of the Discloser. In addition, within 30 days after termination of this Agreement, Recipient shall (i) promptly return all tangible materials containing such Confidential Information to Discloser, (ii) remove all Confidential Information (and any copies thereof) from any computer systems of the Recipient, its contractors and its distributors, and confirm in writing that all materials containing Confidential Information have been destroyed or returned to Discloser, as applicable, by Recipient. Recipient shall cause its affiliates, agents, contractors, and employees to strictly comply with the foregoing.</p>
                <h5>9. No Warranties.</h5>
                <p>CUSTOMER EXPRESSLY UNDERSTANDS AND AGREES THAT ALL USE OF THE LICENSED SOFTWARE IS AT CUSTOMER'S SOLE RISK AND THAT THE LICENSED SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE." DOCKER, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS MAKE NO EXPRESS WARRANTIES AND DISCLAIM ALL IMPLIED WARRANTIES REGARDING THE LICENSED SOFTWARE, INCLUDING IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT, TOGETHER WITH ANY AND ALL WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE IN TRADE. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM DOCKER OR ELSEWHERE SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN THIS AGREEMENT. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, DOCKER, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS DO NOT REPRESENT OR WARRANT TO YOU THAT: (A) CUSTOMER'S USE OF THE LICENSED SOFTWARE WILL MEET CUSTOMER'S REQUIREMENTS, OR (B) CUSTOMER'S USE OF THE LICENSED SOFTWARE WILL BE UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR. NOTWITHSTANDING THE FOREGOING, NOTHING HEREIN SHALL EXCLUDE OR LIMIT DOCKER'S WARRANTY OR LIABILITY FOR LOSSES WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW. CUSTOMER UNDERSTANDS AND ACKNOWLEDGES THAT THE LICENSED SOFTWARE IS NOT DESIGNED, INTENDED OR WARRANTED FOR USE IN HAZARDOUS ENVIRONMENTS REQUIRING FAIL-SAFE CONTROLS, INCLUDING WITHOUT LIMITATION, OPERATION OF NUCLEAR FACILITIES, AIRCRAFT NAVIGATION OR COMMUNICATION SYSTEMS, AIR TRAFFIC CONTROL, AND LIFE SUPPORT OR WEAPONS SYSTEMS.</p>
                <h5>10. Indemnification by Customer.</h5>
                <p>Customer agrees to hold harmless and indemnify Docker and its subsidiaries, affiliates, officers, agents, employees, advertisers, licensors, suppliers or partners from and against any third party claim arising from or in any way related to Customer's breach of this Agreement, use of the Licensed Software, or violation of applicable laws, rules or regulations in connection with the Licensed Software, including any liability or expense arising from all claims, losses, damages (actual and consequential), suits, judgments, litigation costs and attorneys' fees, of every kind and nature. In such a case, Docker will provide Customer with written notice of such claim, suit or action.</p>
                <h5>11. Limitation of Liability.</h5>
                <h5>11.1 Exclusion of Damages</h5>
                <p>Exclusion of Damages. CUSTOMER EXPRESSLY UNDERSTANDS AND AGREES THAT DOCKER, ITS SUBSIDIARIES AND AFFILIATES, AND ITS LICENSORS SHALL NOT BE LIABLE TO CUSTOMER FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL CONSEQUENTIAL OR EXEMPLARY DAMAGES INCURRED BY CUSTOMER, HOWEVER CAUSED AND UNDER ANY THEORY OF LIABILITY, INCLUDING, BUT NOT LIMITED TO, ANY LOSS OF PROFIT (WHETHER INCURRED DIRECTLY OR INDIRECTLY), ANY LOSS OF GOODWILL OR BUSINESS REPUTATION, ANY LOSS OF DATA SUFFERED, COST OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, OR OTHER INTANGIBLE LOSS. THE FOREGOING LIMITATIONS ON DOCKER'S LIABILITY SHALL APPLY WHETHER OR NOT DOCKER HAS BEEN ADVISED OF OR SHOULD HAVE BEEN AWARE OF THE POSSIBILITY OF ANY SUCH LOSSES ARISING. NOTWITHSTANDING THE FOREGOING, NOTHING HEREIN SHALL EXCLUDE OR LIMIT DOCKER'S LIABILITY FOR LOSSES WHICH MAY NOT BE LAWFULLY EXCLUDED OR LIMITED BY APPLICABLE LAW.</p>
                <h5>11.2 Liability Cap</h5>
                <p>THE TOTAL LIABILITY OF DOCKER ARISING OUT OF OR RELATED TO THIS AGREEMENT WILL NOT EXCEED USD $100.</p>
                <h5>12. Export Restrictions.</h5>
                <p>Customer understands that the Licensed Software may contain encryption technology and other software programs that may require an export license from the U.S. State Department and that export or re-export of the Licensed Software to certain entities (such as a foreign government and its subdivisions) and certain countries is prohibited. Customer acknowledges that it will comply with all applicable export and import control laws and regulations of the United States and the foreign jurisdiction in which the Licensed Software is used and, in particular, Customer will not export or re-export the Licensed Software without all required United States and foreign government licenses. Customer will defend, indemnify, and hold harmless Docker and its suppliers and licensors from and against any violation of such laws or regulations by Customer or any of its agents, officers, directors or employees.</p>
                <h5>13. Miscellaneous.</h5>
                <p>The Licensed Software and any other software covered under this Agreement are "commercial items" as that term is defined at 48 C.F.R. 2.101; consisting of "commercial computer software" and "commercial computer software documentation" as such terms are used in 48 C.F.R. 12.212. Consistent with 48 C.F.R. 12.212 and 48 C.F.R. 227.7202-1 through 227.7202-4, all U.S. Government end users acquire the Licensed Software and any other software and documentation covered under this Agreement with only those rights set forth herein. This Agreement will be governed by the laws of the State of California without reference to conflict of law principles. Each party agrees to submit to the exclusive jurisdiction of the courts located within the county of San Francisco, California to resolve any legal matter arising from this Agreement. Neither party may assign any of its rights or obligations under this Agreement, whether by operation of law or otherwise, without the prior written consent of the other party (not to be unreasonably withheld). Notwithstanding the foregoing, Docker may assign the entirety of its rights and obligations under this Agreement, without consent of the Customer, to its affiliate or in connection with a merger, acquisition, corporate reorganization, or sale of all or substantially all of its assets. The application of the UN Convention of International Sale of Goods to this Agreement is disclaimed in its entirety. Together with any Order Forms, this is the entire agreement between the parties relating to the subject matter hereof. This Agreement (including applicable Order Forms) shall control over any additional or different terms of any correspondence, order, confirmation, invoice or similar document, even if accepted in writing by both parties, and waivers and amendments of any provision of this Agreement shall be effective only if made by non-preprinted agreements indicating specifically what sections of this Agreement are affected, signed by both parties and clearly understood by both parties to be an amendment or waiver. The failure of either party to enforce its rights under this Agreement at any time for any period shall not be construed as a waiver of such rights. If any provision of this Agreement is held invalid or unenforceable, the remainder of this Agreement will continue in full force and effect and the invalid or unenforceable provision shall be reformed to the extent necessary to make it valid and enforceable.</p>
              </div>
            </Block>
          </Card>
        </div>
      </div>
    </div>
    );
  }
}
