opam-version: "1"
version: "4.02.3"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.02/ocaml-4.02.3.tar.gz"
build: [
  ["./configure" "-prefix" prefix "-with-debug-runtime"]
  [make "world.opt"]
  [make "install"]
]
packages: [
  "base-unix"
  "base-bigarray"
  "base-threads"
  "base-ocamlbuild"
]
patches: ["https://github.com/ocaml/ocaml/commit/24c118d7.diff"]
env: [[CAML_LD_LIBRARY_PATH = "%{lib}%/stublibs"]]
