name: Release Notes PR Trigger

on:
  pull_request:
    types: [opened]
    paths:
      - content/manuals/desktop/release-notes.md

jobs:
  trigger:
    runs-on: ubuntu-24.04
    if: github.repository_owner == 'docker'
    steps:
      - name: Save PR details
        run: |
          cat <<'EOF' > pr-details.json
          {
            "url": "${{ github.event.pull_request.html_url }}",
            "title": "${{ github.event.pull_request.title }}",
            "author": "${{ github.event.pull_request.user.login }}"
          }
          EOF

      - name: Upload PR details
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7
        with:
          name: pr-details
          path: pr-details.json
